import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.scss";

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Bouncing | Matter.js",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className={`${geistMono.className}`}>{children}</body>
        </html>
    );
}
